---
# tasks file for wordpress

    - name: Downloading wordpress
      unarchive:
        src: http://www.wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Renaming sample wordpress config file
      command: "mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php"

    - name: Updating WordPress config file
      lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp={{ item.regexp }} line={{ item.line }}
      with_items:
        - {'regexp': "define\\( 'DB_NAME', '(database_name_here)+' \\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
        - {'regexp': "define\\( 'DB_USER', '(username_here)+' \\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
        - {'regexp': "define\\( 'DB_PASSWORD', '(password_here)+' \\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
        - {'regexp': "define\\( 'DB_HOST', '(localhost)+' \\);", 'line': "define('DB_HOST', '{{wp_mysql_host}}');"}

    - name: Update default Apache site
      lineinfile:
       dest=/etc/httpd/conf/httpd.conf
       line="DocumentRoot /var/www/html/wordpress"

    - name: Update SELinux Policy to Allow Apache to Connect Database
      command: '/usr/sbin/setsebool -P httpd_can_network_connect_db 1'

